experiment_name: 'DatasetDebugger'

trainer:
  max_epochs: 3

model:
  class_path: models.dataset_debugging_model.DatasetDebuggingModel
  init_args:
    is_two_dim: True

data:
  class_path: data.split_step_generator.SplitStepGenerator
  init_args:
    batch_size: 10
    seq_len: 32
    dispersion: 0.5
    nonlinearity: 0.02
    pulse_width: 10
    z_end: 100
    dz: 0.1
    z_stride: 1000
    dim_t: 4096
    dispersion_compensate: False
    num_blocks: 16
    n_train_batches: 2
    n_val_batches: 2
    n_test_batches: 2
    two_dim_data: true
    device: available
    pulse_amplitudes: null
    pulse_amplitudes_seed: 42